### ISSUE TITLE
App changes to dark mode then crashes upon trying to click on a habit.

### ISSUE THREAD

**Issue by LiquidZulu** [Crazy-Marvin/ToDont#103]
## :writing_hand: Describe the bug
When I open the app it is in light mode (which is not the correct system theme), when I click on the habit it changes to dark mode, then when I click it again the app crashes

## :bomb: Steps to reproduce
1. open the app
2. Click on the x next to the habit

## :wrench: Expected behavior
I expected that it would log it in some way, but as I have never successfully used the app I cannot say

## :camera: Screenshots
https://imgur.com/a/x4K8qyM

## :iphone: Tech info
- Device: Google Pixel 3a
- OS: GrapheneOS RQ3A.210905.001.2021091407
- App Version: 1.2

## :page_facing_up: Additional context
GrapheneOS does not have Google Play or MicroG, nor did the app ask for any permissions upon opening the first time.

**Comment by Romern** [comment]
Can confirm this:
```
FATAL EXCEPTION: main
Process: rocks.poopjournal.todont, PID: 31104
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackground(android.graphics.drawable.Drawable)' on a null object reference
 at rocks.poopjournal.todont.Adapters.HabitsAdapter$2.onClick(HabitsAdapter.java:171)
 at android.view.View.performClick(View.java:7448)
 at android.view.View.performClickInternal(View.java:7425)
 at android.view.View.access$3600(View.java:810)
 at android.view.View$PerformClick.run(View.java:28305)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7664)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

* Device: Pocophone F1
* OS: LineageOS4MicroG 18.1 (20211102)
* App Version: 1.3

**Comment by CrazyMarvin** [comment]
What do you think about this, @arafaatqureshi?
May switching to the "new approach" help?

**Comment by jasonhfuller** [comment]
I'm also experiencing the same issue on Nexus 5x and pixel 5a.

**Comment by CrazyMarvin** [comment]
We updated the appearance with the latest update. It should not crash anymore.
May you test that on your Pixel with GrapheneOS, @LiquidZulu? Do you use GrapheneOS too or the stock Google ROM, @jasonhfuller? A test on your side would be much appreciated any way too.

**Comment by LiquidZulu** [comment]
It doesn't crash but I get stuck in an endless loop of:
1. click tick
2. see splash screen saying "the reverse to-do list ... and the next morning start off with the fresh list."

**EDIT:** this is based on downloading from f-droid, I don't know if that will be the new version or not.

**Comment by CrazyMarvin** [comment]
F-Droid should have the latest version 1.5 already.
May you share a screen recording with us? This seems very strange.
You said that the app does not crash. Was that the case when you initially created this issue? If I combine your initial recording and latest message correctly, the app's behavior did change (although it is not fixed).

**Comment by CrazyMarvin** [comment]
> F-Droid should have the latest version 1.5 already.
> May you share a screen recording with us? This seems very strange.
> You said that the app does not crash. Was that the case when you initially created this issue? If I combine your initial recording and latest message correctly, the app's behavior did change (although it is not fixed).
