### ISSUE TITLE
Create Contributing.md Template

### ISSUE THREAD

**Issue by LuluNwenyi** [Crazy-Marvin/ToDont#104]
For future contributions, having a contribution guideline file would make it easier for open source newbies(like me 😅) to get started. @CrazyMarvin, If you would let me, I can be assigned to this.

**Comment by CrazyMarvin** [comment]
Sure, that is a great idea. 👍
I already created a CONTRIBUTING.md file in the .github folder 8 months ago but I was too lazy to add something unfortunately. 😅

**Comment by LuluNwenyi** [comment]
Alright I'll get to it😊

**Comment by LuluNwenyi** [comment]
Hi @CrazyMarvin, I have submitted a PR for this issue. See here: [Contributing.md PR](https://github.com/Crazy-Marvin/ToDont/pull/105)

**Comment by CrazyMarvin** [comment]
Thank you very much for your contribution, @LuluNwenyi! 🙏
