### ISSUE TITLE
[UX issue] Save button not accessible after typing

### ISSUE THREAD

**Issue by LuluNwenyi** [Crazy-Marvin/ToDont#107]
Hi @CrazyMarvin,
When you click the field to type in an attempt to create a new label or task for a list, the keyboard covers up the save button and the return button only creates a new paragraph.

**Comment by CrazyMarvin** [comment]
Oh, you're right. 😅
Are you available to open a PR which fixes this?

**Comment by LuluNwenyi** [comment]
I'm not a java developer but if you explain what needs to be fixed I could figure it out😅

**Comment by arafaatqureshi** [comment]
Thanks @LuluNwenyi  for you input, Please once try your mobile default back button to quit the keyboard and then save, please try this and update me with the results please.

**Comment by LuluNwenyi** [comment]
Hi @arafaatqureshi, I apologize for the late response. It's still the same.

**Comment by CrazyMarvin** [comment]
Is it working fine now, @LuluNwenyi?
