### ISSUE TITLE
Second Line Of Task Not Shown Fully

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#136]
## :writing_hand: Describe the bug
When entering a task which does not fit in one line the second line is only partially shown

## :bomb: Steps to reproduce

1. Click on the **+** and enter a task which is longer than one line (e.g. `Go outside when there is a hazard warning`)
2. Note and category are optional
3. Click on **Save**

## :wrench: Expected behavior
A second line should be shown fully. I am not sure how to handle even longer tasks.

## :camera: Screenshots
![bug](https://user-images.githubusercontent.com/15004217/173255972-037d8193-b388-4184-9e01-18e9c4ac258d.jpg)

## :iphone: Tech info
- Device: OnePlus Nord
- OS: Android 11
- App Version: v1.5

## :page_facing_up: Additional context
Let's discuss here how we should handle tasks which are longer than two lines.

**Comment by arafaatqureshi** [comment]
the height properties were fixed to be responsive according to the text.
