### ISSUE TITLE
navigation bar color

### ISSUE THREAD

**Issue by andsofine** [Crazy-Marvin/ToDont#137]
change navigation bar color in light theme to background color (instead of black)

**Comment by CrazyMarvin** [comment]
May you please share a screenshot, @andsofine? The navigation bar is not black in light mode on my device so I would like to see how it looks on your phone. Please also share the brand, model and Android version.

**Comment by andsofine** [comment]
the same on the main menu.
![Screenshot_20220709-171058.png](https://user-images.githubusercontent.com/99369164/178109481-27283a3f-690d-4f18-9507-fe651827af9d.png)

there seems to be a problem at the top as well.


android 12 grapheneos
Pixel 4 xl

**Comment by CrazyMarvin** [comment]
Oh, I see it now.

May you please check, @arafaatqureshi?

A OnePlus Nord running Android 12 behaves fine.

**Comment by arafaatqureshi** [comment]
I have checked the code, there is no such property added in the code to make the corners round.  not the the top nav bar neither in the background gradient.

**Comment by CrazyMarvin** [comment]
Do you still have this issue? Are you able to create a fix for this, @andsofine?

**Comment by andsofine** [comment]
it's still there. 
unfortunately I'm not a programmer

**Comment by CrazyMarvin** [comment]
Is the issue gone somehow, @andsofine? 😅

**Comment by CrazyMarvin** [comment]
I will close this because it seems to be a device-specific issue.
Let us know if you have another device for testing the behaviour, @andsofine. Thanks for reporting! 👍
