### ISSUE TITLE
Switch to Vector Graphics

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#139]
Vector graphics offer a higher resolution and are smaller than raster graphics.  
I think using vector graphics instead of the raster graphics have positive effects only and no  downsides.
Let me know if you see any issues with this though of which I am currently unaware of.

**Comment by CrazyMarvin** [comment]
I attached a ZIP archive with all vector graphics.
[svg.zip](https://github.com/Crazy-Marvin/ToDont/files/9226230/svg.zip)

**Comment by CrazyMarvin** [comment]
Here is the .zip with the launcher icon.
[ToDont_LauncherIcon.zip](https://github.com/Crazy-Marvin/ToDont/files/9570202/ToDont_LauncherIcon.zip)

**Comment by CrazyMarvin** [comment]
@subeep, are you interested in doing this?

**Comment by subeep** [comment]
Sure.

**Comment by subeep** [comment]
> @subeep, are you interested in doing this?

Sure.

**Comment by subeep** [comment]
Btw I think it's better to use the settings gear icon instead of the three vertical dots because it makes more sense as there is no dropdown and looks a bit more coherent.

**Comment by CrazyMarvin** [comment]
Fixed in To Don't v1.9 (closed by #164)
