### ISSUE TITLE
Support Per-app Language Preferences

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#175]
Android 13 introduced the option for users to set a [per-app language preference](https://developer.android.com/guide/topics/resources/app-languages). It would be nice if we could support this too.

**Comment by Georgezogos** [comment]
Hello, I can work on that. Can you specify it a little bit more?

**Comment by CrazyMarvin** [comment]
> Hello, I can work on that. Can you specify it a little bit more?

That are great news.

Did you read the article I linked?

For me, it would be fine to support just Android 13+ and skip the lower versions.

The app doesn't have an in-app language picker and it should stay like that.

**Comment by Georgezogos** [comment]
Hello, great. I have read the article. I saw that you have already different language files in the project. Should I just create the xml file and the configuration for the multiple language support?

**Comment by CrazyMarvin** [comment]
> Hello, great. I have read the article. I saw that you have already different language files in the project. Should I just create the xml file and the configuration for the multiple language support?
> 

Yes, that would be great.

Do you have an Android 13 device to test it?

**Comment by CrazyMarvin** [comment]
Implemented in `v2.1.0`.
