### ISSUE TITLE
[bug] app crash when adding a habit without a label

### ISSUE THREAD

**Issue by starspritechippy** [Crazy-Marvin/ToDont#187]
## :writing_hand: Describe the bug

when creating a habit without first adding a label and saving the habit, the app crashes and can't be opened until clearing all data.

## :bomb: Steps to reproduce

1. Open the app after installing/clearing data
2. Don't create a label, immediately tap the (+) Button to create a habit
3. enter a name and note
4. Tap Save

## :wrench: Expected behavior

The habit saves with a "no label set" message, where a label should be. Alternatively, prompt the user to create a label first.

## :iphone: Tech info
- Device:  Samsung Galaxy A72
- OS:  Android 13 / Stock ROM
- App Version:  1.9

**Comment by CrazyMarvin** [comment]
Thanks for the bug report. We will look into it.

**Comment by arafaatqureshi** [comment]
Looking into it. 
will update it with an alert message to add a label first.

**Comment by CrazyMarvin** [comment]
This should be fixed with `v2.0`.
Please let me know if that works for you, @starspritechippy. Thanks for reporting it. 😘
