### ISSUE TITLE
feature request: Dark mode

### ISSUE THREAD

**Issue by AlvinChan-gh** [Crazy-Marvin/ToDont#188]
After using your app to note down my to-don'ts at night, I noticed how eye-straining the app is to use at night even at low brightness. Would it be possible to implement a dark mode, such that it can be more easily used at night?

**Comment by CrazyMarvin** [comment]
> After using your app to note down my to-don'ts at night, I noticed how eye-straining the app is to use at night even at low brightness. Would it be possible to implement a dark mode, such that it can be more easily used at night?
> 

Hey,
a night mode is already included.
You may find it when you click on the three dots on the right top.
