### ISSUE TITLE
Hosted Weblate Integration

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#2]

**Comment by comradekingu** [comment]
I'll happily help put this on Hosted Weblate to remove libre software from Crowdin.
https://docs.weblate.org/en/latest/admin/continuous.html#continuous-localization

**Comment by CrazyMarvin** [comment]
Alright, I setup [https://hosted.weblate.org/projects/todont/](https://hosted.weblate.org/projects/todont/) and added you. You can prepare a Pull Request that adds continuous localization. The app is in an early alpha status at the moment but a beta will be available next month. So don't wonder when many strings change until then.

**Comment by comradekingu** [comment]
@Crazy If you set up https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github that should be good to go. Then shut down Crowdin :)

**Comment by CrazyMarvin** [comment]
Perfect, I just added the webhook.

**Comment by CrazyMarvin** [comment]
The integration seems to be working fine, doesn't it, @comradekingu?

**Comment by comradekingu** [comment]
Indeed it does. Had a go in the nb_NO section earlier.
No push address set up in https://hosted.weblate.org/settings/todont/to-dont/#vcs
but I don't know if that is needed.

**Comment by CrazyMarvin** [comment]
I am not sure either so I just put it there to be safe. 👌

By the way, I noticed that in the `fastlane/metadata/android/nb-NO/` folder the `full_description.txt` is missing. May you have a look?

**Comment by comradekingu** [comment]
@CrazyMarvin There was a word I couldn't remember yesterday, so I did it today :)
The metadata strings could do with some improvements, but looks like it works now.

**Comment by CrazyMarvin** [comment]
Do you know how I can disable `video.txt `for translation on Hosted Weblate?
I just marked it as read-only but I am not sure if that is the right way to go. 

![read-only](https://user-images.githubusercontent.com/15004217/113514755-c6da4080-9570-11eb-978f-e355f97ce6d9.png)

**Comment by CrazyMarvin** [comment]
@comradekingu, I am also wondering how I can get rid of the entry `night (generated) (night)` in Weblate. 🤔
Do you have an idea?

![weblate](https://user-images.githubusercontent.com/15004217/115039502-ca56bb80-9ed0-11eb-94fb-e8efbd0782dc.jpg)

**Comment by comradekingu** [comment]
@CrazyMarvin Found it in https://hosted.weblate.org/projects/todont/to-dont/night/#delete

**Comment by CrazyMarvin** [comment]
Thanks! 👍

**Comment by CrazyMarvin** [comment]
> @CrazyMarvin Found it in https://hosted.weblate.org/projects/todont/to-dont/night/#delete

That seems to delete the whole file, doesn't it? 
At the moment we need it for the app to work. My idea was to keep it in the code and just mark it as "unnecessary" for translators.

**Comment by CrazyMarvin** [comment]
![maro](https://user-images.githubusercontent.com/15004217/145694066-bff0b41a-62df-4c1b-9f09-b6e48525f615.PNG)
![labeldnt](https://user-images.githubusercontent.com/15004217/145694068-f7bb957e-46af-4dde-87a0-d3e071a40ca3.PNG)
I marked it as read-only and gave it a label called `do-not-translate-please`. This should be fine.

**Comment by CrazyMarvin** [comment]
![locked](https://user-images.githubusercontent.com/15004217/145694232-47e0e9a9-6bb1-43c1-9892-81214a2c9ef2.PNG)

I am having this notice since three days.

**Comment by comradekingu** [comment]
@CrazyMarvin Something is wrong with the German file https://hosted.weblate.org/projects/todont/to-dont/#alerts
https://github.com/Crazy-Marvin/ToDont/commit/2b35fd8e0222e427ecb4ab586a16f55f4ece62b1#diff-7049c01dbaca09e41462205bc840bb2bdf6766f0b832e1ff68059c7fdfafadc8L1
I don't really understand the point of.

Similar to other changes in that commit, but values-de is the only thing changed 3 days ago in but https://github.com/Crazy-Marvin/ToDont/tree/development/app/src/main/res

**Comment by CrazyMarvin** [comment]
I manually reset it. Now it should be working again.
