### ISSUE TITLE
delete habits

### ISSUE THREAD

**Issue by wunschadresse** [Crazy-Marvin/ToDont#205]
## :warning: Is your feature request related to a problem? Please describe.
I would like to remove a habit, which is no longer relevant, but cannot find that Option.

## :bulb: Describe the solution you'd like
A *delete* button in the edit menu of a habit.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

## additional
make protocol items removable as well.

**Comment by CrazyMarvin** [comment]
Deleting items is done by swiping them right.

This is something that could be shown in a small tutorial (#34).

**Comment by CrazyMarvin** [comment]
You may check `v3.0.0` and let me know what you think about the tutorial.
