### ISSUE TITLE
Import/Export feature for backup/reinstallations of app.

### ISSUE THREAD

**Issue by TehDomic** [Crazy-Marvin/ToDont#271]
## :warning: Is your feature request related to a problem? Please describe

No built in ability to export/backup my appdata without root.

If I were to uninstall or switch phones/devices, all my to don't lists would disappear.
## :bulb: Describe the solution you'd like

Adding a feature to backup/restore app data to a file I can store for backup.
## :bar_chart: Describe alternatives you've considered

Unable to root my phone at the moment, I can't backup any intended way.
## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by Sauhard74** [comment]
can i work on to this issue>?

**Comment by CrazyMarvin** [comment]
> can i work on to this issue>?

Yes, that would be awesome. 👍

**Comment by CrazyMarvin** [comment]
The feature is live with `v3.0.0` thanks to @theftzoku.
