### ISSUE TITLE
Add a small tutorial

### ISSUE THREAD

**Issue by fwsmit** [Crazy-Marvin/ToDont#34]
After creating a task it's not entirely clear how to mark it as avoided or done. I figured it out now, but a small tutorial or text in the description of the app would be helpful.

**Comment by CrazyMarvin** [comment]
Hey, that is a great idea. May you propose something?

**Comment by LuluNwenyi** [comment]
Hi @CrazyMarvin I’d like to work on the documentation 😅

**Comment by CrazyMarvin** [comment]
That would be awesome, @LuluNwenyi! 😃
Please let me know if you will come upon any questions.
Thank you very much.

**Comment by CrazyMarvin** [comment]
@LuluNwenyi, are you still up for this task?
@fwsmit, may you propose a little text for the tutorial which would have made the use of To Don't more comfortable for you?

**Comment by fwsmit** [comment]
I'm sorry, I don't actively use the app anymore. The interface is already clearer IIRC.

**Comment by CrazyMarvin** [comment]
The feature is live with `v3.0.0` thanks to @theftzoku.
