### ISSUE TITLE
Bigger buttons 

### ISSUE THREAD

**Issue by fwsmit** [Crazy-Marvin/ToDont#35]
The buttons to mark as done or avoided are quite small. I would suggest making them a bit bigger.
I've never developed on Android before, but I would like to volunteer for this one if you can give me some build instructions :)

**Comment by CrazyMarvin** [comment]
Yes, I noticed that too. 😬

We planned to use a swipe gesture instead like it is used in Gmail for example. I am not sure why @arafaatqureshi  did not implement it. May you help @fwSmit with the PR, @arafaatqureshi?

When you open the project in Android Studio it should build directly.

**Comment by CrazyMarvin** [comment]
I also noticed that the swipe gesture for deleting is not working in the Labels section. We will add that.
For marking a habit as done we will think about something.

**Comment by tfry-git** [comment]
It would also help to have (a lot) more spacing between the two buttons. E.g. avoided on the left, done on the right of the label, or something. The main problem to me is that I will sometimes hit the wrong button.

**Comment by arafaatqureshi** [comment]
Noted, will update till weekend :)

**Comment by CrazyMarvin** [comment]
With v1.2 the buttons got a bit bigger but we still need to improve the UX. What do you think?
