### ISSUE TITLE
Submit To Don't on F-Droid

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ToDont#4]
[https://f-droid.org/en/contribute/](https://f-droid.org/en/contribute/)

**Comment by CrazyMarvin** [comment]
[RFP Issue](https://gitlab.com/fdroid/rfp/-/issues/1690)

**Comment by CrazyMarvin** [comment]
A [few notes on  the Fastlane structure](https://gitlab.com/fdroid/rfp/-/issues/1690#note_544064797):
- Please do not copy the same screenshots to all languages. What is not present in e.g. **pl**, will automatically be picked from en-US (**fallback**)
- Same goes for things like `title.tx`, `video.txt` & the changelogs

**Comment by goyalyashpal** [comment]
done??
i found this on fdroid: https://f-droid.org/packages/rocks.poopjournal.todont/

**Comment by CrazyMarvin** [comment]
[Yes, it is done.](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8743)
