### ISSUE TITLE
App crashes when adding label in very specific circumstance

### ISSUE THREAD

**Issue by analpi** [Crazy-Marvin/ToDont#44]
## :writing_hand: Describe the bug
If I try to add a label to a habit that doesn't already have one, To Don't crashes.

## :bomb: Steps to reproduce
1. Don't create any labels after installing the app.
2. Make a habit.
3. Create a label.
4. Try adding the new label to the habit.
5. Sad face as app crashes.

## :wrench: Expected behavior
The label should be added. If this can't be done, prevent creating habits until a label exists.

## :iphone: Tech info
- Device: Samsung A20
- OS: 10
- App Version: 1.0 beta

**Comment by CrazyMarvin** [comment]
May you please check if the bug is gone with **v1.1**, @xander-page? It might be fixed already. 😀
But @arafaatqureshi will check it again because he will have access to a Samsung A20 in a few days. 👌

**Comment by CrazyMarvin** [comment]
@xander-page, does this still occur in v1.3?

**Comment by CrazyMarvin** [comment]
Please re-open if this issue is not solved. It looks fine on the devices I used for testing.
