### ISSUE TITLE
"Continue" and "Done" buttons not visible on portrait oriented screens

### ISSUE THREAD

**Issue by tfry-git** [Crazy-Marvin/ToDont#58]
## :writing_hand: Describe the bug
Most likely this issue will only be seen on some screen widths. Anyway, for me the continue and done-buttons for text fields go out of screen in portrait orientation. As "enter" inputs a new line, instead of accepting the input, this makes it impossible to enter/update labels or notes.

## :bomb: Steps to reproduce

1. Switch display to portrait mode
2. On bottom of main screen hit "+"
3. Enter some text for the lable
4. Try to submit it ... you cannot, as the "continue" button is not reachable.

**Comment by CrazyMarvin** [comment]
Hey, thanks for the report. May you please add a screenshot and information about your device?

**Comment by CrazyMarvin** [comment]
![o2](https://user-images.githubusercontent.com/15004217/147791537-21de8dde-bae0-452c-abfd-2c3ba598777c.jpg)

![o1](https://user-images.githubusercontent.com/15004217/147791538-dd955675-da65-432c-918b-1ba824f24cac.jpg)

The app is working fine in portrait mode too. Maybe you are referring to the keyboard handling (see #107). 🤔
I will close this issue though. Let me know if I did not get your point correctly please.
