### ISSUE TITLE
crazymartin.com uses an invalid security certificate.

### ISSUE THREAD

**Issue by morriscox** [Crazy-Marvin/ToDont#84]
crazymartin.com uses an invalid security certificate. The certificate expired on July 19, 2021 at 4:37 AM. The current time is August 23, 2021 at 6:59 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by CrazyMarvin** [comment]
Hey, the domain I use is crazymarvin.com.
Did I put crazymartin.com somewhere by mistake? Thanks for your help.

**Comment by morriscox** [comment]
Sorry about that. I managed to mistype it 5 times. It's surprising that I managed to make it here. Bleah.

**Comment by CrazyMarvin** [comment]
Don't worry. 😂
