### ISSUE TITLE
Missing strings in the Weblate project

### ISSUE THREAD

**Issue by sakci** [Crazy-Marvin/ToDont#94]
Notice the non-Turkish strings (including the Day, Week, Month, Year abbreviations). Please add them to the Weblate project.

![Screenshot_20210904-204307_Yaplmayacaklar](https://user-images.githubusercontent.com/87014067/132103742-2e8178d8-76b4-4b5e-bc7e-1767460bde25.png)
![Screenshot_20210904-204210_Yaplmayacaklar](https://user-images.githubusercontent.com/87014067/132103745-2a26b2f6-b8b0-4b72-a94a-036847a15dbe.png)
![Screenshot_20210904-204228_Yaplmayacaklar](https://user-images.githubusercontent.com/87014067/132103746-b7f5876c-08e8-4e98-ac31-79fbec177b46.png)

**Comment by CrazyMarvin** [comment]
Thanks for mentioning this, @sakci. We will check this.

**Comment by CrazyMarvin** [comment]
We added some more strings with the latest release but the Day, Week, Month and Year abbreviations and the welcome screen are still hard-coded. Please have a look, @arafaatqureshi.

**Comment by CrazyMarvin** [comment]
The three toasts when changing the appearance are missing too.

https://user-images.githubusercontent.com/15004217/147791165-3c3c46ce-0433-4339-bf14-fd6f8b539f79.mp4

**Comment by CrazyMarvin** [comment]
I made the toasts translateable. 

May you please check if I forget something, @subeep? The Day, Week, Month and Year abbreviations seen in the first screenshot from @sakci are definitely missing. Thanks! 🙏

**Comment by CrazyMarvin** [comment]
@arafaatqureshi, may you please make the Day, Week, Month and Year abbreviations translateable?

**Comment by CrazyMarvin** [comment]
Now everything should be translateable finally. 🚀
